### ISSUE TITLE
Too expensive overengineering solution

### ISSUE THREAD

**Issue by adv4000** [jdhollis/bastions-on-demand#2]
To develop this from the scratch will take ~10 hours, if you get 100$ per hour it will cost 1000$ to your employer/customer.
For how long you can keep t3.nano running as bastion host for 1000$ and provisioning it within 1 min?

Just by reading and trying to implement this solution will take 1-2 hours, again 100$-200$ just to implement?
Spin up simple EC2 in 1 min, save money. Or write simple terraform to spin EC2 in your VPC in 30 lines of code.

This is Great example of **Over-Engineering** and employer/customer should be avoided to work with engineers like this.

Make great **simple** solutions!

**Comment by jdhollis** [comment]
That’s one way to look at it.

Alas, simple isn’t easy. It’s trade-offs all the way down.

(Oh—and I don’t bill hourly.)
